### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by 0xDRRB** [bnielsen1965/pi-pico-c-rtc#1]
Hello,
I'm currently working on a Pico-based TOTP code display project and I'm using your code (ds3231.c and ds3231.h) to manage my DS3231 module.
Your repository doesn't specify any license (GPL, MIT or other). Is it open source, and what are the conditions of use?
Have a nice day.

**Comment by bnielsen1965** [comment]
Hello @0xDRRB 

Thank you for pointing out my license oversight. I added a new commit with an MIT license.
